### ISSUE TITLE
Dependency tracking

### ISSUE THREAD

**Issue by mateolan** [ICICLE-ai/Smartfoodshed_VA#1]
Need to track package dependencies, and upgrade to latest versions. 
See below for error on a fresh vue install:

While resolving: @vue/cli-plugin-router@4.5.17
Found: @vue/cli-service@5.0.1
node_modules/@vue/cli-service
  dev @vue/cli-service@"~5.0.0" from the root project
  peer @vue/cli-service@"^3.0.0 || ^4.0.0 || ^5.0.0-0" from @vue/cli-plugin-babel@5.0.1
  node_modules/@vue/cli-plugin-babel
    dev @vue/cli-plugin-babel@"~5.0.0" from the root project
  peer @vue/cli-service@"^3.0.0 || ^4.0.0 || ^5.0.0-0" from @vue/cli-plugin-eslint@5.0.1
  node_modules/@vue/cli-plugin-eslint
    dev @vue/cli-plugin-eslint@"~5.0.0" from the root project
  peer @vue/cli-service@"^3.0.0 || ^4.0.0 || ^5.0.0-0" from @vue/cli-plugin-vuex@5.0.1
  node_modules/@vue/cli-plugin-vuex
    dev @vue/cli-plugin-vuex@"~5.0.0" from the root project
    @vue/cli-plugin-vuex@"^5.0.1" from @vue/cli-service@5.0.1
  peer @vue/cli-service@"^3.0.0 || ^4.0.0 || ^5.0.0-0" from @vue/cli-plugin-router@5.0.4
  node_modules/@vue/cli-service/node_modules/@vue/cli-plugin-router
    @vue/cli-plugin-router@"^5.0.1" from @vue/cli-service@5.0.1

Could not resolve dependency:
peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-router@4.5.17
node_modules/@vue/cli-plugin-router
  dev @vue/cli-plugin-router@"~4.5.15" from the root project

Conflicting peer dependency: @vue/cli-service@4.5.17
node_modules/@vue/cli-service
  peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-router@4.5.17
  node_modules/@vue/cli-plugin-router
    dev @vue/cli-plugin-router@"~4.5.15" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by yasmineTYM** [comment]
> Instead of running `npm install` could you try running `npm install --legacy-peer-deps` , that should work. If it works please let me know, I'll update the README file.

Thanks, Harsh! it works. 
<img width="1552" alt="Screen Shot 2022-05-28 at 3 14 13 PM" src="https://user-images.githubusercontent.com/18289816/170839744-b2bec56f-42d6-4901-a953-6709da6d4870.png">

**Comment by yasmineTYM** [comment]
I also update the readme file, feel free to further improve it if that is not clear. Thanks for the help.
