### ISSUE TITLE
Node labels

### ISSUE THREAD

**Issue by prhuber** [ICICLE-ai/Smartfoodshed_VA#2]
It would be great to see the full entity name when you hover over a node in the graph view.

**Comment by yasmineTYM** [comment]
Added ~

**Comment by yasmineTYM** [comment]
<img width="174" alt="Screen Shot 2022-05-26 at 3 05 06 PM" src="https://user-images.githubusercontent.com/18289816/170571887-1e7f2b38-f555-4a8d-b90d-c858f52bb01b.png">
